/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AntDesignX: typeof import('./src/components/ant-design-x.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinyGrid: typeof import('@opentiny/vue-grid')['default']
    TinyGridColumn: typeof import('@opentiny/vue-grid-column')['default']
    TinyTag: typeof import('@opentiny/vue-tag')['default']
  }
}
